### ISSUE TITLE
Minor JSON issue : "appType"

### ISSUE THREAD

**Issue by GaiusCoffey** [SergioMorchon/fitbit-sdk-scaffolding#1]
Hi,
Love the extension, but have noticed that appType in package.json is never reset from "appType": "app" regardless of the app type I am building.
Thanks,
Gaius

**Comment by SergioMorchon** [comment]
Hi @GaiusCoffey , thanks for the report! I've found and fixed the issue (see [the changeset](https://github.com/SergioMorchon/fitbit-sdk-scaffolding/commit/29f87ad24a036f430fccd4531f449953ad6f79b2)).
The update is also available
