### ISSUE TITLE
Image.from doesn't match examples from Fitbit

### ISSUE THREAD

**Issue by GaiusCoffey** [SergioMorchon/fitbit-sdk-scaffolding#5]
Hi,
As per this thread on Discord... https://discord.com/channels/355793206182412290/360916874902372352/930419433346834462 it looks like the "Image" ts definitions may be suspect. 
The Fitbit examples have Image.from(somethingOrOther, string|null) where the ts is looking for Image.from(string)... (apologies for the pseudo code... I don't _actually_ know the correct definitions as I cannot find any docs for Image.from!
G

**Comment by GaiusCoffey** [comment]
PS: Now that I have it working, it looks like it needs to also include:
.from(buffer:ArrayBuffer,mimeType:String) where mimeType is the image format.

**Comment by GaiusCoffey** [comment]
Got it:
Hexxeh posted https://discord.com/channels/355793206182412290/360916874902372352/930458283947458560
export const Image: {
        /**
         * Create a promise that a new image will be created from a Data URI
         * @see https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs
         * @param uri The URI containing the data representing the image
         */
        from(uri: string): Promise<Image>

        /**
         * Create a promise that a new image will be created from an array buffer and a mime type
         * @param data The data from which to create the image.
         * @param mimeType The MIME type of the data.
         */
        from(data: ArrayBuffer, mimeType: SourceMimeType): Promise<Image>
    }

**Comment by SergioMorchon** [comment]
I think you're talking about https://github.com/SergioMorchon/fitbit-sdk-types
I'll review this!

**Comment by SergioMorchon** [comment]
Indeed, it's fixed here: https://github.com/SergioMorchon/fitbit-sdk-types/pull/178
